import { writeFile, access } from 'node:fs/promises';
import { constants } from 'node:fs';

/**
 * The default manifest filename generated by `mcp-offline-bundler init`.
 */
export const DEFAULT_MANIFEST_FILENAME = 'mcp.manifest.yaml';

/**
 * The sample manifest content written by `init` (PRD section 10.1 / 15).
 *
 * The example servers come from this template, not from the core build code.
 * Versions are exact (no latest / * / ^ / ~ / >=) so the bundle is
 * reproducible and version-pinned.
 */
export const SAMPLE_MANIFEST_CONTENT = `# mcp.manifest.yaml — describes which MCP servers to put in the offline bundle.
#
# Versions MUST be exact (no latest / * / ^ / ~ / >=). Run
# \`npm view <package> version\` to find a current version and pin it here.
#
# This bundle targets linux-x64 / Node >=20 / npm / stdio MCP servers only.
bundle:
  name: browser-mcp-offline-bundle
  target: linux-x64
  node: ">=20"
  archiveName: mcp-offline-bundle-linux-x64

install:
  packageManager: npm
  omitDev: true
  env:
    # Never download browsers as part of the bundle build.
    PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: "1"

servers:
  - name: chrome-devtools
    package: chrome-devtools-mcp
    version: "1.1.1"
    bin: chrome-devtools-mcp
    transport: stdio
    args:
      - "--browser-url=http://127.0.0.1:9222"
      - "--no-usage-statistics"
      - "--no-performance-crux"
    env:
      CHROME_DEVTOOLS_MCP_NO_UPDATE_CHECKS: "1"
      CHROME_DEVTOOLS_MCP_NO_USAGE_STATISTICS: "1"
    smokeTestArgs:
      - "--help"

  - name: playwright
    package: "@playwright/mcp"
    version: "0.0.75"
    bin: playwright-mcp
    transport: stdio
    args:
      - "--cdp-endpoint=http://127.0.0.1:9222"
    env:
      PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: "1"
    smokeTestArgs:
      - "--help"

clients:
  claudeDesktop: true
  codex: true
  cursor: true
  genericJson: true
`;

/**
 * Error thrown when `init` would overwrite an existing manifest file.
 */
export class ManifestExistsError extends Error {
  constructor(public readonly path: string) {
    super(
      `Refusing to overwrite existing manifest at ${path}. ` +
        `Remove it first, choose a different --path, or pass --force.`,
    );
    this.name = 'ManifestExistsError';
  }
}

/**
 * Options for {@link writeSampleManifest}.
 */
export interface WriteSampleManifestOptions {
  /** Destination path for the manifest. Defaults to `mcp.manifest.yaml`. */
  path?: string;
  /** Overwrite an existing file instead of failing. Defaults to false. */
  force?: boolean;
}

/**
 * Result of {@link writeSampleManifest}.
 */
export interface WriteSampleManifestResult {
  /** The path the manifest was written to. */
  path: string;
}

/**
 * Write the sample manifest to disk.
 *
 * Refuses to overwrite an existing file unless `force` is set, so users do not
 * accidentally clobber a manifest they have already customised.
 */
export async function writeSampleManifest(
  options: WriteSampleManifestOptions = {},
): Promise<WriteSampleManifestResult> {
  const path = options.path ?? DEFAULT_MANIFEST_FILENAME;
  if (options.force !== true && (await pathExists(path))) {
    throw new ManifestExistsError(path);
  }
  await writeFile(path, SAMPLE_MANIFEST_CONTENT, 'utf8');
  return { path };
}

/**
 * Return true when a filesystem entry exists at `path`.
 */
async function pathExists(path: string): Promise<boolean> {
  try {
    await access(path, constants.F_OK);
    return true;
  } catch {
    return false;
  }
}
